# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_img', models.CharField(blank=True, max_length=512, null=True)),
                ('url_loc', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('money', models.IntegerField(blank=True, null=True)),
                ('money_type', models.CharField(blank=True, max_length=512, null=True)),
                ('product_url', models.CharField(blank=True, max_length=512, null=True)),
                ('starts', models.CharField(blank=True, max_length=512, null=True)),
                ('all_cost', models.CharField(blank=True, max_length=512, null=True)),
                ('supply', models.CharField(blank=True, max_length=512, null=True)),
                ('rate', models.CharField(blank=True, max_length=512, null=True)),
                ('instruction', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'pros',
                'managed': False,
            },
        ),
    ]
